In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as st

In [2]:
tt=st.t.ppf(1-0.02,38)
tt

2.126674020167019

In [3]:
xa=80
xb=75
ua=80
ub=80
sa=5
sb=6
n=20

In [4]:
tc=(xa-xb)/(np.sqrt((25/20)+(36/20)))
tc

2.862991671569341

In [5]:
if tt<tc:
    print("ha is right")
else:
    print("ho is right")
    

ha is right


In [6]:
x=148
u=150
s=5
n=25
p=0.05
df=(n-1)

In [7]:
t_table= st.t.ppf(p,df)
t_table

-1.7108820799094282

In [8]:
t_cal=(x-u)/(s/np.sqrt(n))
t_cal

-2.0

In [9]:
if t_cal<t_table:
    print("ha is righ")
else:
    print("ho is right")

ha is righ


In [10]:
s_x = 90
p_u = 82
p_std = 20
n = 81
ap = 0.05

In [11]:
z_cal = (s_x-p_u)/(p_std/np.sqrt(n))
z_cal

3.5999999999999996

In [12]:
z_table=st.norm.ppf(1-ap)
z_table

1.6448536269514722

In [13]:
if z_cal>z_table:
    print("ha is right")
else:
    print("ha is not right")

ha is right


In [36]:
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [38]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_rows = np.array([sum_r1,sum_r2])
sum_rows

array([120, 115])

In [40]:
sum_c=row1+row2
sum_c

array([75, 75, 45, 40])

In [62]:
exp = []
for i in sum_rows:
    for j in sum_c:
        value = (i*j/235)
        exp.append(value)

In [64]:
exp

[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [68]:
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [80]:
chi_cal=np.sum(np.square(obj - exp)/exp)

In [78]:
chi_table = 7.815
chi_table

7.815

In [82]:
chi_cal

13.788747987117553

In [88]:
if chi_cal>chi_table:
    print("the given data are associate")
else:
    print("the data is not associate")
    

the given data are associate
